### ISSUE TITLE
Final scores in percentage when leaving the game

### ISSUE THREAD

**Issue by marcmueller86** [PanMig/Chemistry-Lab#10]
After entering the exit door, the percentage of the solved elements should be shown. E.g if we have 10 molecules, and the student finished 5 of them, the ratio should be accessible to track in the resulting scene.

**Comment by PanMig** [comment]
The percentage is not visible in the game , however it is accessible through the game manager.

Also you can add the tracking in the Game manager => ExitSimulation() where you just track the int playerProgress.

**Comment by marcmueller86** [comment]
Okay, I guess it is `public float playerProgress;`?

**Comment by PanMig** [comment]
Yes but it is an `int`.
