### ISSUE TITLE
There is an error with the unity sdk after receiving a strategy

### ISSUE THREAD

**Issue by marcmueller86** [PanMig/Chemistry-Lab#13]
We have to check why there is an error when receiving a strategy at the beginning. 
This could have to causes:

- The HTTP request is not working probably
- The processing of the strategy with null leads to an error in the molecule manager

**Comment by PanMig** [comment]
There is the error in the console, it will be good if we can fix this.

```
ArgumentNullException: Argument cannot be null.
Parameter name: _unity_self
goedle_sdk.detail.GoedleWebRequest.get_isNetworkError () (at Assets/goedle_io/Scripts/detail/GoedleWebRequest.cs:39)
goedle_sdk.detail.GoedleHttpClient+<postJSONRequest>c__Iterator2.MoveNext () (at Assets/goedle_io/Scripts/detail/GoedleHttpClient.cs:129)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```

**Comment by marcmueller86** [comment]
I currently cannot reproduce it, I'm not 100% sure if this now is fixed due to the changes in the molecule manager, in the coroutine which executes the request strategy major changes where made. I will observe the behavior.

**Comment by PanMig** [comment]
This is fixed Marc, thanks!!!
