### ISSUE TITLE
Strike line??

### ISSUE THREAD

**Issue by jimver04** [PanMig/Chemistry-Lab#19]
I went from naming to construction and back to naming the molecule name is striked:
![image](https://user-images.githubusercontent.com/1898502/39686198-5135bfd0-51d0-11e8-8842-63553bd667e0.png)

Alcohols are written correct now :)

**Comment by PanMig** [comment]
This is a new feature to show the user that he has completed this specific molecule. He can name it again if he wants but he want get any extra score. It is used to help the user remember which molecules had been named. The same applies to construction.
