### ISSUE TITLE
MouseTranslate.cs Line 2 script bug

### ISSUE THREAD

**Issue by jimver04** [PanMig/Chemistry-Lab#21]
Pano, 

I 've tried to compile the game chemtestUnity (the one I have sent you on Friday for compiling) with Unity 2018.1 and it was not recognizing UnityEngine.Collections in MouseTranslate.cs. When I changed it to System.Collections it was ok, it compiled successfully :). Can you check if System.Collections is working with 2017.3? 

The spot is in Line 2

```
using UnityEngine;
using UnityEngine.Collections;

public class MouseTranslate : MonoBehaviour
{
...
```
I will change the asset in github in wordpressunity3deditor also.

Have fun in Creta,
D.

**Comment by PanMig** [comment]
Hello Dimitri,

Yes that's a good point I have checked the script and there is no reason for System.Collection to exist, so you can delete it in case it creates a problem. The library is not used in the script.

Panos
